import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.old.module.css';
import { ComicCard } from '../components/ComicCard';

import keys from '../config/keys';

const testComic = {
  imageUrl: 'https://d1466nnw0ex81e.cloudfront.net/n_iv/600/5827198.jpg',
  title: {
    name: '20 Fists (2021 Source Point Press)',
    publisher: {
      name: 'Source Point Press',
      seoFriendlyName: 'source-point-press',
      id: '5f1e0645502f0e81003bafd7',
    },
    seoFriendlyName: '20-fists-2021-source-point-press',
    id: '60bb75ec4ca2b31b94200d34',
  },
  seoFriendlyName: '2',
  id: '60bb75ec4ca2b31b94200d35',
};

export default function Home({ comics }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          {comics.issues.slice(0, 10).map((comic) => {
            return (
              <div className={styles.card}>
                <ComicCard comic={comic} />;
              </div>
            );
          })}
        </div>
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

// This function gets called at build time
export async function getServerSideProps() {
  // Call an external API endpoint to get posts
  const res = await fetch(`${keys.comicApi}catalog/issue?date=2021-06-02`);
  const comics = await res.json();

  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: {
      comics,
    },
  };
}
